#cloud-config

runcmd:
    - export C_FORCE_ROOT="true"
    - export BROKER_USER=
    - export BROKER_PASS=
    - export FLOATING_IP=
    - export OS_AUTH_URL=
    - export OS_TENANT_ID=
    - export OS_TENANT_NAME=
    - export OS_PROJECT_NAME=
    - export OS_USERNAME=
    - export OS_PASSWORD=
    - export OS_REGION_NAME=
    - cd /home/ubuntu/molnProject
    - celery worker -A proj &